# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, hosc, aeson, conduit, dataDefault, fastLogger, hjsmin, hspec
, httpConduit, monadControl, monadLogger, persistent
, persistentSqlite, persistentTemplate, prettyShow, resourcet, shakespeare
, text, transformers, waiExtra, waiLogger, warp, yaml, yesod
, yesodBin, yesodAuth, yesodCore, yesodForm, yesodStatic, yesodTest
}:

cabal.mkDerivation (self: {
  pname = "chordster";
  version = "0.0.0";
  src=./.;
  isLibrary = true;
  isExecutable = true;
  buildTools = [ yesodBin ];
  buildDepends = [
    hosc aeson conduit dataDefault fastLogger hjsmin httpConduit
    monadControl monadLogger persistent persistentSqlite
    persistentTemplate prettyShow shakespeare text waiExtra waiLogger warp yaml
    yesod yesodAuth yesodCore yesodForm yesodStatic
  ];
  testDepends = [
    hspec monadLogger persistent persistentSqlite resourcet
    transformers yesod yesodCore yesodTest
  ];
  meta = {
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
